# Generated by Django 3.2.4 on 2021-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=50)),
                ('skills_text', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
