# Generated by Django 3.2.4 on 2021-07-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20210616_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=1000)),
                ('user', models.CharField(max_length=200)),
                ('questionId', models.IntegerField()),
            ],
        ),
    ]
