# Generated by Django 3.2 on 2021-07-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='interview',
        ),
    ]
